export const gameData = {
    liveId: "",
    gameId: "",
    periods: {
        "1": 20,
        "2": 20,
        "3": 20,
        OT1: 10,
    },
    gameNumber: "Game MCG-2",
    gameType: "Playoff",
    date: "Aug 23, 2024, 7:07 PM",
    location: "Poirier Sport and Leisure Complex",
    gameStatus: "Final",
    home: {
        id: 251012,
        title: "Orangeville Northmen",
        division: "Minto Cup",
        record: "0-2-0",
        logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
        finalScore: "6",
        sog: 56,
        roster: {
            coaches: [
                {
                    firstName: "RYLAN",
                    id: "866733",
                    lastName: "HARTLEY",
                    position: "assistant_coach",
                    signature: "",
                    status: "coaching",
                },
                {
                    firstName: "ANDREW",
                    id: "866729",
                    lastName: "SUITOR",
                    position: "assistant_coach",
                    signature: "",
                    status: "coaching",
                },
                {
                    firstName: "DJ",
                    id: "866731",
                    lastName: "CLEVELY",
                    position: "assistant_coach",
                    signature: "",
                    status: "coaching",
                },
                {
                    firstName: "NICK",
                    id: "866730",
                    lastName: "ROSE",
                    position: "manager",
                    signature: "",
                    status: "coaching",
                },
                {
                    firstName: "PHIL",
                    id: "866727",
                    lastName: "SANDERSON",
                    position: "assistant_coach",
                    signature: "",
                    status: "coaching",
                },
                {
                    firstName: "MARY",
                    id: "866728",
                    lastName: "LALANCETTE",
                    position: "trainer",
                    signature: "",
                    status: "coaching",
                },
                {
                    firstName: "RUSTY",
                    id: "866732",
                    lastName: "KRUGER",
                    position: "head_coach",
                    signature:
                        "https://storage.googleapis.com/download/storage/v1/b/gamesheet-files/o/1A0CE591-2440-43D7-B1CA-6ED6401CF350.jpg?generation=1724472981993904&alt=media",
                    status: "coaching",
                },
            ],
            players: [
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "COLM",
                    g: 0,
                    ga: null,
                    id: "3748604",
                    lastName: "BARNETT  ★",
                    number: "15",
                    pim: 0,
                    position: "forward",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "TREY",
                    g: 1,
                    ga: null,
                    id: "3748608",
                    lastName: "DEERE",
                    number: "91",
                    pim: 0,
                    position: "forward",
                    pts: 1,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 3,
                        goals: 1,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "BRIAN",
                    g: 0,
                    ga: null,
                    id: "3748616",
                    lastName: "JACKMAN  ★",
                    number: "26",
                    pim: 0,
                    position: "forward",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "alternate_captain",
                    firstName: "DONNY",
                    g: 0,
                    ga: null,
                    id: "3748624",
                    lastName: "SCOTT",
                    number: "23",
                    pim: 0,
                    position: "forward",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 1,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 1,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "BOWIE",
                    g: 1,
                    ga: null,
                    id: "3748606",
                    lastName: "HORSMAN  ★",
                    number: "81",
                    pim: 0,
                    position: "forward",
                    pts: 2,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 2,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "AIDEN",
                    g: 0,
                    ga: null,
                    id: "3748610",
                    lastName: "LONG",
                    number: "27",
                    pim: 0,
                    position: "forward",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "SEAN",
                    g: 0,
                    ga: null,
                    id: "3748609",
                    lastName: "COSTIGAN ☆",
                    number: "28",
                    pim: 0,
                    position: "forward",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 1,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 1,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "JAKE",
                    g: 0,
                    ga: null,
                    id: "3748628",
                    lastName: "SPALLINA",
                    number: "71",
                    pim: 0,
                    position: "forward",
                    pts: 1,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "captain",
                    firstName: "JADEN",
                    g: 0,
                    ga: null,
                    id: "3748605",
                    lastName: "CIAPPARA",
                    number: "4",
                    pim: 0,
                    position: "forward",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 1,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "DANTE",
                    g: 0,
                    ga: null,
                    id: "3748601",
                    lastName: "BOWEN  ★",
                    number: "3",
                    pim: 0,
                    position: "defence",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 2,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "OWEN",
                    g: 0,
                    ga: null,
                    id: "3748622",
                    lastName: "RAHN",
                    number: "18",
                    pim: 0,
                    position: "forward",
                    pts: 2,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 1,
                        goals: 1,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 1,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "CAM",
                    g: 0,
                    ga: null,
                    id: "3748621",
                    lastName: "PACK  ★",
                    number: "55",
                    pim: 0,
                    position: "forward",
                    pts: 1,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "NATE",
                    g: 0,
                    ga: null,
                    id: "3748629",
                    lastName: "RUFF  ★",
                    number: "16",
                    pim: 2,
                    position: "forward",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 1,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "ELIJAH",
                    g: 0,
                    ga: null,
                    id: "3748613",
                    lastName: "EDWARDS",
                    number: "13",
                    pim: 2,
                    position: "forward",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 2,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "DYLAN",
                    g: 1,
                    ga: null,
                    id: "3748614",
                    lastName: "SANDERSON ☆",
                    number: "11",
                    pim: 0,
                    position: "forward",
                    pts: 3,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 1,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "alternate_captain",
                    firstName: "LIAM",
                    g: 3,
                    ga: null,
                    id: "3748627",
                    lastName: "MATTHEWS",
                    number: "7",
                    pim: 0,
                    position: "forward",
                    pts: 3,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 2,
                        goals: 3,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "COLE",
                    g: 0,
                    ga: null,
                    id: "3748617",
                    lastName: "TEEPLE  ★",
                    number: "14",
                    pim: 0,
                    position: "forward",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 2,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "JOEY",
                    g: 0,
                    ga: null,
                    id: "3748611",
                    lastName: "SPALLINA  ★",
                    number: "22",
                    pim: 0,
                    position: "forward",
                    pts: 2,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 2,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
            ],
            goalies: [
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "CONNOR",
                    g: 0,
                    ga: 9,
                    id: "3748620",
                    lastName: "O'TOOLE ★",
                    number: "39",
                    pim: null,
                    position: "goalie",
                    pts: 0,
                    rc: 0,
                    sa: 49,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: true,
                    status: "playing",
                    svpct: 0.816,
                    toi: 3584,
                    yc: 0,
                    gaa: 9.040178571428571,
                },
                {
                    a: null,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "LINDYN",
                    g: null,
                    ga: null,
                    id: "3748626",
                    lastName: "HILL  ★",
                    number: "30",
                    pim: null,
                    position: "goalie",
                    pts: null,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                    gaa: 0,
                },
            ],
        },
        penalties: [
            {
                eventType: "penalty",
                time: "02:59",
                period: "1",
                homeTeam: true,
                major: false,
                commitedBy: {
                    type: "players",
                    title: "NATE RUFF  ★",
                    id: "3748629",
                    number: "16",
                },
                servedBy: {
                    id: "",
                    title: "ELIJAH EDWARDS",
                    number: "13",
                },
                penaltyType: {
                    title: "Illegal Cross-Checking",
                    duration: "2",
                    class: "minor",
                },
                team: {
                    id: 251012,
                    title: "Orangeville Northmen",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                },
            },
            {
                eventType: "penalty",
                time: "00:15",
                period: "1",
                homeTeam: true,
                major: false,
                commitedBy: {
                    type: "players",
                    title: "ELIJAH EDWARDS",
                    id: "3748613",
                    number: "13",
                },
                servedBy: {
                    id: "",
                    title: "ELIJAH EDWARDS",
                    number: "13",
                },
                penaltyType: {
                    title: "Illegal Cross-Checking",
                    duration: "2",
                    class: "minor",
                },
                team: {
                    id: 251012,
                    title: "Orangeville Northmen",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                },
            },
        ],
        goals: [
            {
                eventType: "goal",
                time: "12:44",
                period: "1",
                homeTeam: true,
                powerPlay: true,
                gameWinningGoal: false,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3748627",
                    title: "LIAM MATTHEWS",
                    number: "7",
                    trackingNumber: "1",
                    totalGoalCount: "4",
                },
                assist1By: {
                    id: "3748611",
                    title: "JOEY SPALLINA  ★",
                    number: "22",
                    trackingNumber: "1",
                    totalGoalCount: "3",
                },
                team: {
                    id: 251012,
                    title: "Orangeville Northmen",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                },
            },
            {
                eventType: "goal",
                time: "01:45",
                period: "1",
                homeTeam: true,
                powerPlay: false,
                gameWinningGoal: false,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3748627",
                    title: "LIAM MATTHEWS",
                    number: "7",
                    trackingNumber: "2",
                    totalGoalCount: "5",
                },
                assist1By: {
                    id: "3748622",
                    title: "OWEN RAHN",
                    number: "18",
                    trackingNumber: "1",
                    totalGoalCount: "2",
                },
                assist2By: {
                    id: "3748614",
                    title: "DYLAN SANDERSON ☆",
                    number: "11",
                    trackingNumber: "1",
                    totalGoalCount: "2",
                },
                team: {
                    id: 251012,
                    title: "Orangeville Northmen",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                },
            },
            {
                eventType: "goal",
                time: "09:09",
                period: "2",
                homeTeam: true,
                powerPlay: false,
                gameWinningGoal: false,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3748627",
                    title: "LIAM MATTHEWS",
                    number: "7",
                    trackingNumber: "3",
                    totalGoalCount: "6",
                },
                assist1By: {
                    id: "3748606",
                    title: "BOWIE HORSMAN  ★",
                    number: "81",
                    trackingNumber: "1",
                    totalGoalCount: "1",
                },
                assist2By: {
                    id: "3748614",
                    title: "DYLAN SANDERSON ☆",
                    number: "11",
                    trackingNumber: "2",
                    totalGoalCount: "3",
                },
                team: {
                    id: 251012,
                    title: "Orangeville Northmen",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                },
            },
            {
                eventType: "goal",
                time: "06:40",
                period: "2",
                homeTeam: true,
                powerPlay: false,
                gameWinningGoal: false,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3748614",
                    title: "DYLAN SANDERSON ☆",
                    number: "11",
                    trackingNumber: "1",
                    totalGoalCount: "1",
                },
                assist1By: {
                    id: "3748622",
                    title: "OWEN RAHN",
                    number: "18",
                    trackingNumber: "2",
                    totalGoalCount: "3",
                },
                assist2By: {
                    id: "3748628",
                    title: "JAKE SPALLINA",
                    number: "71",
                    trackingNumber: "1",
                    totalGoalCount: "1",
                },
                team: {
                    id: 251012,
                    title: "Orangeville Northmen",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                },
            },
            {
                eventType: "goal",
                time: "08:26",
                period: "3",
                homeTeam: true,
                powerPlay: false,
                gameWinningGoal: false,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3748608",
                    title: "TREY DEERE",
                    number: "91",
                    trackingNumber: "1",
                    totalGoalCount: "2",
                },
                assist1By: {
                    id: "3748621",
                    title: "CAM PACK  ★",
                    number: "55",
                    trackingNumber: "1",
                    totalGoalCount: "1",
                },
                team: {
                    id: 251012,
                    title: "Orangeville Northmen",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                },
            },
            {
                eventType: "goal",
                time: "02:36",
                period: "3",
                homeTeam: true,
                powerPlay: false,
                gameWinningGoal: false,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3748606",
                    title: "BOWIE HORSMAN  ★",
                    number: "81",
                    trackingNumber: "1",
                    totalGoalCount: "3",
                },
                assist1By: {
                    id: "3748611",
                    title: "JOEY SPALLINA  ★",
                    number: "22",
                    trackingNumber: "2",
                    totalGoalCount: "4",
                },
                team: {
                    id: 251012,
                    title: "Orangeville Northmen",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                },
            },
        ],
    },
    visitor: {
        id: 251013,
        title: "Coquitlam Adanacs",
        division: "Minto Cup",
        record: "2-0-0",
        logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
        finalScore: "9",
        sog: 49,
        roster: {
            coaches: [
                {
                    firstName: "AIDEN",
                    id: "871014",
                    lastName: "YORKE",
                    position: "assistant_coach",
                    signature: "",
                    status: "coaching",
                },
                {
                    firstName: "SAQIB",
                    id: "871018",
                    lastName: "NIAZ",
                    position: "trainer",
                    signature: "",
                    status: "coaching",
                },
                {
                    firstName: "RICHARD",
                    id: "871015",
                    lastName: "HANSON",
                    position: "assistant_coach",
                    signature: "",
                    status: "coaching",
                },
                {
                    firstName: "PATRICK",
                    id: "871019",
                    lastName: "COYLE",
                    position: "head_coach",
                    signature:
                        "https://storage.googleapis.com/download/storage/v1/b/gamesheet-files/o/B22005EF-E708-4770-B56E-8FEC0BFBBDCC.jpg?generation=1724472982575233&alt=media",
                    status: "coaching",
                },
                {
                    firstName: "YETHAN",
                    id: "871016",
                    lastName: "TICEHURST",
                    position: "assistant_coach",
                    signature: "",
                    status: "coaching",
                },
                {
                    firstName: "SCOTT",
                    id: "871013",
                    lastName: "WORTLEY",
                    position: "",
                    signature: "",
                    status: "away",
                },
                {
                    firstName: "CHRIS",
                    id: "871017",
                    lastName: "GILL",
                    position: "assistant_coach",
                    signature: "",
                    status: "coaching",
                },
            ],
            players: [
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "NATHAN",
                    g: 2,
                    ga: null,
                    id: "3770188",
                    lastName: "CHALMERS",
                    number: "7",
                    pim: 0,
                    position: "forward",
                    pts: 2,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 1,
                        goals: 1,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "REMO",
                    g: 0,
                    ga: null,
                    id: "3770182",
                    lastName: "SCHENATO",
                    number: "17",
                    pim: 2,
                    position: "defence",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 1,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "COLTON",
                    g: 0,
                    ga: null,
                    id: "3770167",
                    lastName: "KENNETT",
                    number: "21",
                    pim: 0,
                    position: "defence",
                    pts: 1,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 3,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "NOAH",
                    g: 2,
                    ga: null,
                    id: "3770190",
                    lastName: "MANNING",
                    number: "3",
                    pim: 0,
                    position: "forward",
                    pts: 5,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 6,
                        goals: 2,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 2,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "BENJAMIN",
                    g: 0,
                    ga: null,
                    id: "3770172",
                    lastName: "COGHILL",
                    number: "36",
                    pim: 0,
                    position: "defence",
                    pts: 2,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 2,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "DAVID",
                    g: 1,
                    ga: null,
                    id: "3770183",
                    lastName: "CHARNEY",
                    number: "15",
                    pim: 0,
                    position: "forward",
                    pts: 3,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 2,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "BRODIE",
                    g: 0,
                    ga: null,
                    id: "3770185",
                    lastName: "KENT",
                    number: "10",
                    pim: 0,
                    position: "defence",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 1,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "JORDAN",
                    g: 0,
                    ga: null,
                    id: "3770180",
                    lastName: "REED",
                    number: "24",
                    pim: 0,
                    position: "defence",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 1,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "ROBERT",
                    g: 0,
                    ga: null,
                    id: "3770186",
                    lastName: "TURPIN",
                    number: "12",
                    pim: 0,
                    position: "defence",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 1,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "JAXON",
                    g: 0,
                    ga: null,
                    id: "3770174",
                    lastName: "FRIDGE",
                    number: "66",
                    pim: 0,
                    position: "defence",
                    pts: 1,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "PARKER",
                    g: 0,
                    ga: null,
                    id: "3770179",
                    lastName: "KENNEDY",
                    number: "27",
                    pim: 0,
                    position: "forward",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 3,
                        goals: 1,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "JAXON",
                    g: 0,
                    ga: null,
                    id: "3770178",
                    lastName: "DILLON",
                    number: "29",
                    pim: 0,
                    position: "forward",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 1,
                        goals: 5,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 1,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "TY",
                    g: 0,
                    ga: null,
                    id: "3770181",
                    lastName: "BANKS",
                    number: "22",
                    pim: 0,
                    position: "defence",
                    pts: 1,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "NATHAN",
                    g: 0,
                    ga: null,
                    id: "3770175",
                    lastName: "MILLER",
                    number: "93",
                    pim: 0,
                    position: "defence",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 0,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "CONNOR",
                    g: 0,
                    ga: null,
                    id: "3770177",
                    lastName: "NOCK",
                    number: "26",
                    pim: 0,
                    position: "defence",
                    pts: 0,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 1,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "RYAN",
                    g: 0,
                    ga: null,
                    id: "3770187",
                    lastName: "COLSEY",
                    number: "13",
                    pim: 0,
                    position: "forward",
                    pts: 1,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 2,
                        goals: 2,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 1,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "CODY",
                    g: 4,
                    ga: null,
                    id: "3770169",
                    lastName: "MALAWSKY",
                    number: "2",
                    pim: 2,
                    position: "forward",
                    pts: 5,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 2,
                        goals: 1,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
                {
                    a: 1,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "RYAN",
                    g: 0,
                    ga: null,
                    id: "3770189",
                    lastName: "FAVARO",
                    number: "4",
                    pim: 0,
                    position: "forward",
                    pts: 1,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 1,
                        goals: 2,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                },
            ],
            goalies: [
                {
                    a: 1,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "JACK",
                    g: 0,
                    ga: 6,
                    id: "3770170",
                    lastName: "KASK",
                    number: "35",
                    pim: null,
                    position: "goalie",
                    pts: 1,
                    rc: 0,
                    sa: 56,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: true,
                    status: "playing",
                    svpct: 0.893,
                    toi: 3600,
                    yc: 0,
                    gaa: 6,
                },
                {
                    a: null,
                    added_at_game_time: false,
                    affiliated: false,
                    duty: "",
                    firstName: "TRISTAN",
                    g: null,
                    ga: null,
                    id: "3770166",
                    lastName: "LOMAS",
                    number: "1",
                    pim: null,
                    position: "goalie",
                    pts: null,
                    rc: 0,
                    sa: null,
                    season: {
                        assists: 0,
                        goals: 0,
                    },
                    starting: false,
                    status: "playing",
                    svpct: null,
                    toi: null,
                    yc: 0,
                    gaa: 0,
                },
            ],
        },
        penalties: [
            {
                eventType: "penalty",
                time: "13:49",
                period: "1",
                homeTeam: false,
                major: false,
                commitedBy: {
                    type: "players",
                    title: "REMO SCHENATO",
                    id: "3770182",
                    number: "17",
                },
                servedBy: {
                    id: "",
                    title: "REMO SCHENATO",
                    number: "17",
                },
                penaltyType: {
                    title: "Illegal Cross-Checking",
                    duration: "2",
                    class: "minor",
                },
                team: {
                    id: 251013,
                    title: "Coquitlam Adanacs",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                },
            },
            {
                eventType: "penalty",
                time: "10:32",
                period: "3",
                homeTeam: false,
                major: false,
                commitedBy: {
                    type: "players",
                    title: "CODY MALAWSKY",
                    id: "3770169",
                    number: "2",
                },
                servedBy: {
                    id: "",
                    title: "CODY MALAWSKY",
                    number: "2",
                },
                penaltyType: {
                    title: "Delay of Game",
                    duration: "2",
                    class: "minor",
                },
                team: {
                    id: 251013,
                    title: "Coquitlam Adanacs",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                },
            },
        ],
        goals: [
            {
                eventType: "goal",
                time: "12:22",
                period: "1",
                homeTeam: false,
                powerPlay: false,
                gameWinningGoal: false,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3770188",
                    title: "NATHAN CHALMERS",
                    number: "7",
                    trackingNumber: "1",
                    totalGoalCount: "2",
                },
                assist1By: {
                    id: "3770183",
                    title: "DAVID CHARNEY",
                    number: "15",
                    trackingNumber: "1",
                    totalGoalCount: "3",
                },
                assist2By: {
                    id: "3770172",
                    title: "BENJAMIN COGHILL",
                    number: "36",
                    trackingNumber: "1",
                    totalGoalCount: "1",
                },
                team: {
                    id: 251013,
                    title: "Coquitlam Adanacs",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                },
            },
            {
                eventType: "goal",
                time: "02:59",
                period: "1",
                homeTeam: false,
                powerPlay: false,
                gameWinningGoal: false,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3770190",
                    title: "NOAH MANNING",
                    number: "3",
                    trackingNumber: "1",
                    totalGoalCount: "3",
                },
                assist1By: {
                    id: "3770174",
                    title: "JAXON FRIDGE",
                    number: "66",
                    trackingNumber: "1",
                    totalGoalCount: "1",
                },
                team: {
                    id: 251013,
                    title: "Coquitlam Adanacs",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                },
            },
            {
                eventType: "goal",
                time: "11:09",
                period: "2",
                homeTeam: false,
                powerPlay: false,
                gameWinningGoal: false,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3770169",
                    title: "CODY MALAWSKY",
                    number: "2",
                    trackingNumber: "1",
                    totalGoalCount: "2",
                },
                assist1By: {
                    id: "3770170",
                    title: "JACK KASK",
                    number: "35",
                    trackingNumber: "1",
                    totalGoalCount: "1",
                },
                team: {
                    id: 251013,
                    title: "Coquitlam Adanacs",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                },
            },
            {
                eventType: "goal",
                time: "07:17",
                period: "2",
                homeTeam: false,
                powerPlay: false,
                gameWinningGoal: false,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3770169",
                    title: "CODY MALAWSKY",
                    number: "2",
                    trackingNumber: "2",
                    totalGoalCount: "3",
                },
                team: {
                    id: 251013,
                    title: "Coquitlam Adanacs",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                },
            },
            {
                eventType: "goal",
                time: "03:27",
                period: "2",
                homeTeam: false,
                powerPlay: false,
                gameWinningGoal: false,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3770188",
                    title: "NATHAN CHALMERS",
                    number: "7",
                    trackingNumber: "2",
                    totalGoalCount: "3",
                },
                assist1By: {
                    id: "3770167",
                    title: "COLTON KENNETT",
                    number: "21",
                    trackingNumber: "1",
                    totalGoalCount: "1",
                },
                assist2By: {
                    id: "3770172",
                    title: "BENJAMIN COGHILL",
                    number: "36",
                    trackingNumber: "2",
                    totalGoalCount: "2",
                },
                team: {
                    id: 251013,
                    title: "Coquitlam Adanacs",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                },
            },
            {
                eventType: "goal",
                time: "00:50",
                period: "2",
                homeTeam: false,
                powerPlay: false,
                gameWinningGoal: false,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3770183",
                    title: "DAVID CHARNEY",
                    number: "15",
                    trackingNumber: "1",
                    totalGoalCount: "1",
                },
                assist1By: {
                    id: "3770190",
                    title: "NOAH MANNING",
                    number: "3",
                    trackingNumber: "1",
                    totalGoalCount: "7",
                },
                assist2By: {
                    id: "3770189",
                    title: "RYAN FAVARO",
                    number: "4",
                    trackingNumber: "1",
                    totalGoalCount: "2",
                },
                team: {
                    id: 251013,
                    title: "Coquitlam Adanacs",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                },
            },
            {
                eventType: "goal",
                time: "11:55",
                period: "3",
                homeTeam: false,
                powerPlay: false,
                gameWinningGoal: true,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3770169",
                    title: "CODY MALAWSKY",
                    number: "2",
                    trackingNumber: "3",
                    totalGoalCount: "4",
                },
                assist1By: {
                    id: "3770190",
                    title: "NOAH MANNING",
                    number: "3",
                    trackingNumber: "2",
                    totalGoalCount: "8",
                },
                assist2By: {
                    id: "3770187",
                    title: "RYAN COLSEY",
                    number: "13",
                    trackingNumber: "1",
                    totalGoalCount: "3",
                },
                team: {
                    id: 251013,
                    title: "Coquitlam Adanacs",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                },
            },
            {
                eventType: "goal",
                time: "11:37",
                period: "3",
                homeTeam: false,
                powerPlay: false,
                gameWinningGoal: false,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3770190",
                    title: "NOAH MANNING",
                    number: "3",
                    trackingNumber: "2",
                    totalGoalCount: "4",
                },
                assist1By: {
                    id: "3770169",
                    title: "CODY MALAWSKY",
                    number: "2",
                    trackingNumber: "1",
                    totalGoalCount: "3",
                },
                assist2By: {
                    id: "3770181",
                    title: "TY BANKS",
                    number: "22",
                    trackingNumber: "1",
                    totalGoalCount: "1",
                },
                team: {
                    id: 251013,
                    title: "Coquitlam Adanacs",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                },
            },
            {
                eventType: "goal",
                time: "07:23",
                period: "3",
                homeTeam: false,
                powerPlay: false,
                gameWinningGoal: false,
                shg: false,
                en: false,
                goalScorer: {
                    id: "3770169",
                    title: "CODY MALAWSKY",
                    number: "2",
                    trackingNumber: "4",
                    totalGoalCount: "5",
                },
                assist1By: {
                    id: "3770190",
                    title: "NOAH MANNING",
                    number: "3",
                    trackingNumber: "3",
                    totalGoalCount: "9",
                },
                assist2By: {
                    id: "3770183",
                    title: "DAVID CHARNEY",
                    number: "15",
                    trackingNumber: "2",
                    totalGoalCount: "4",
                },
                team: {
                    id: 251013,
                    title: "Coquitlam Adanacs",
                    logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                },
            },
        ],
    },
    isPlayerStatsPrivate: false,
    tables: {
        scoring: {
            title: [
                {
                    id: 251013,
                    title: "Coquitlam Adanacs",
                },
                {
                    id: 251012,
                    title: "Orangeville Northmen",
                },
            ],
            final: ["9", "6"],
            scoresByPeriod: [
                {
                    data: [2, 2],
                    period: "1ST",
                },
                {
                    data: [4, 2],
                    period: "2ND",
                },
                {
                    data: [3, 2],
                    period: "3RD",
                },
            ],
        },
        goalsByPeriod: [
            {
                period: "1ST Period",
                periodEvents: [
                    {
                        eventType: "goal",
                        time: "12:44",
                        period: "1",
                        homeTeam: true,
                        powerPlay: true,
                        gameWinningGoal: false,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3748627",
                            title: "LIAM MATTHEWS",
                            number: "7",
                            trackingNumber: "1",
                            totalGoalCount: "4",
                        },
                        assist1By: {
                            id: "3748611",
                            title: "JOEY SPALLINA  ★",
                            number: "22",
                            trackingNumber: "1",
                            totalGoalCount: "3",
                        },
                        team: {
                            id: 251012,
                            title: "Orangeville Northmen",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                        },
                    },
                    {
                        eventType: "goal",
                        time: "12:22",
                        period: "1",
                        homeTeam: false,
                        powerPlay: false,
                        gameWinningGoal: false,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3770188",
                            title: "NATHAN CHALMERS",
                            number: "7",
                            trackingNumber: "1",
                            totalGoalCount: "2",
                        },
                        assist1By: {
                            id: "3770183",
                            title: "DAVID CHARNEY",
                            number: "15",
                            trackingNumber: "1",
                            totalGoalCount: "3",
                        },
                        assist2By: {
                            id: "3770172",
                            title: "BENJAMIN COGHILL",
                            number: "36",
                            trackingNumber: "1",
                            totalGoalCount: "1",
                        },
                        team: {
                            id: 251013,
                            title: "Coquitlam Adanacs",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                        },
                    },
                    {
                        eventType: "goal",
                        time: "02:59",
                        period: "1",
                        homeTeam: false,
                        powerPlay: false,
                        gameWinningGoal: false,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3770190",
                            title: "NOAH MANNING",
                            number: "3",
                            trackingNumber: "1",
                            totalGoalCount: "3",
                        },
                        assist1By: {
                            id: "3770174",
                            title: "JAXON FRIDGE",
                            number: "66",
                            trackingNumber: "1",
                            totalGoalCount: "1",
                        },
                        team: {
                            id: 251013,
                            title: "Coquitlam Adanacs",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                        },
                    },
                    {
                        eventType: "goal",
                        time: "01:45",
                        period: "1",
                        homeTeam: true,
                        powerPlay: false,
                        gameWinningGoal: false,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3748627",
                            title: "LIAM MATTHEWS",
                            number: "7",
                            trackingNumber: "2",
                            totalGoalCount: "5",
                        },
                        assist1By: {
                            id: "3748622",
                            title: "OWEN RAHN",
                            number: "18",
                            trackingNumber: "1",
                            totalGoalCount: "2",
                        },
                        assist2By: {
                            id: "3748614",
                            title: "DYLAN SANDERSON ☆",
                            number: "11",
                            trackingNumber: "1",
                            totalGoalCount: "2",
                        },
                        team: {
                            id: 251012,
                            title: "Orangeville Northmen",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                        },
                    },
                ],
                type: "goals",
            },
            {
                period: "2ND Period",
                periodEvents: [
                    {
                        eventType: "goal",
                        time: "11:09",
                        period: "2",
                        homeTeam: false,
                        powerPlay: false,
                        gameWinningGoal: false,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3770169",
                            title: "CODY MALAWSKY",
                            number: "2",
                            trackingNumber: "1",
                            totalGoalCount: "2",
                        },
                        assist1By: {
                            id: "3770170",
                            title: "JACK KASK",
                            number: "35",
                            trackingNumber: "1",
                            totalGoalCount: "1",
                        },
                        team: {
                            id: 251013,
                            title: "Coquitlam Adanacs",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                        },
                    },
                    {
                        eventType: "goal",
                        time: "09:09",
                        period: "2",
                        homeTeam: true,
                        powerPlay: false,
                        gameWinningGoal: false,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3748627",
                            title: "LIAM MATTHEWS",
                            number: "7",
                            trackingNumber: "3",
                            totalGoalCount: "6",
                        },
                        assist1By: {
                            id: "3748606",
                            title: "BOWIE HORSMAN  ★",
                            number: "81",
                            trackingNumber: "1",
                            totalGoalCount: "1",
                        },
                        assist2By: {
                            id: "3748614",
                            title: "DYLAN SANDERSON ☆",
                            number: "11",
                            trackingNumber: "2",
                            totalGoalCount: "3",
                        },
                        team: {
                            id: 251012,
                            title: "Orangeville Northmen",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                        },
                    },
                    {
                        eventType: "goal",
                        time: "07:17",
                        period: "2",
                        homeTeam: false,
                        powerPlay: false,
                        gameWinningGoal: false,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3770169",
                            title: "CODY MALAWSKY",
                            number: "2",
                            trackingNumber: "2",
                            totalGoalCount: "3",
                        },
                        team: {
                            id: 251013,
                            title: "Coquitlam Adanacs",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                        },
                    },
                    {
                        eventType: "goal",
                        time: "06:40",
                        period: "2",
                        homeTeam: true,
                        powerPlay: false,
                        gameWinningGoal: false,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3748614",
                            title: "DYLAN SANDERSON ☆",
                            number: "11",
                            trackingNumber: "1",
                            totalGoalCount: "1",
                        },
                        assist1By: {
                            id: "3748622",
                            title: "OWEN RAHN",
                            number: "18",
                            trackingNumber: "2",
                            totalGoalCount: "3",
                        },
                        assist2By: {
                            id: "3748628",
                            title: "JAKE SPALLINA",
                            number: "71",
                            trackingNumber: "1",
                            totalGoalCount: "1",
                        },
                        team: {
                            id: 251012,
                            title: "Orangeville Northmen",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                        },
                    },
                    {
                        eventType: "goal",
                        time: "03:27",
                        period: "2",
                        homeTeam: false,
                        powerPlay: false,
                        gameWinningGoal: false,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3770188",
                            title: "NATHAN CHALMERS",
                            number: "7",
                            trackingNumber: "2",
                            totalGoalCount: "3",
                        },
                        assist1By: {
                            id: "3770167",
                            title: "COLTON KENNETT",
                            number: "21",
                            trackingNumber: "1",
                            totalGoalCount: "1",
                        },
                        assist2By: {
                            id: "3770172",
                            title: "BENJAMIN COGHILL",
                            number: "36",
                            trackingNumber: "2",
                            totalGoalCount: "2",
                        },
                        team: {
                            id: 251013,
                            title: "Coquitlam Adanacs",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                        },
                    },
                    {
                        eventType: "goal",
                        time: "00:50",
                        period: "2",
                        homeTeam: false,
                        powerPlay: false,
                        gameWinningGoal: false,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3770183",
                            title: "DAVID CHARNEY",
                            number: "15",
                            trackingNumber: "1",
                            totalGoalCount: "1",
                        },
                        assist1By: {
                            id: "3770190",
                            title: "NOAH MANNING",
                            number: "3",
                            trackingNumber: "1",
                            totalGoalCount: "7",
                        },
                        assist2By: {
                            id: "3770189",
                            title: "RYAN FAVARO",
                            number: "4",
                            trackingNumber: "1",
                            totalGoalCount: "2",
                        },
                        team: {
                            id: 251013,
                            title: "Coquitlam Adanacs",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                        },
                    },
                ],
                type: "goals",
            },
            {
                period: "3RD Period",
                periodEvents: [
                    {
                        eventType: "goal",
                        time: "11:55",
                        period: "3",
                        homeTeam: false,
                        powerPlay: false,
                        gameWinningGoal: true,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3770169",
                            title: "CODY MALAWSKY",
                            number: "2",
                            trackingNumber: "3",
                            totalGoalCount: "4",
                        },
                        assist1By: {
                            id: "3770190",
                            title: "NOAH MANNING",
                            number: "3",
                            trackingNumber: "2",
                            totalGoalCount: "8",
                        },
                        assist2By: {
                            id: "3770187",
                            title: "RYAN COLSEY",
                            number: "13",
                            trackingNumber: "1",
                            totalGoalCount: "3",
                        },
                        team: {
                            id: 251013,
                            title: "Coquitlam Adanacs",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                        },
                    },
                    {
                        eventType: "goal",
                        time: "11:37",
                        period: "3",
                        homeTeam: false,
                        powerPlay: false,
                        gameWinningGoal: false,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3770190",
                            title: "NOAH MANNING",
                            number: "3",
                            trackingNumber: "2",
                            totalGoalCount: "4",
                        },
                        assist1By: {
                            id: "3770169",
                            title: "CODY MALAWSKY",
                            number: "2",
                            trackingNumber: "1",
                            totalGoalCount: "3",
                        },
                        assist2By: {
                            id: "3770181",
                            title: "TY BANKS",
                            number: "22",
                            trackingNumber: "1",
                            totalGoalCount: "1",
                        },
                        team: {
                            id: 251013,
                            title: "Coquitlam Adanacs",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                        },
                    },
                    {
                        eventType: "goal",
                        time: "08:26",
                        period: "3",
                        homeTeam: true,
                        powerPlay: false,
                        gameWinningGoal: false,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3748608",
                            title: "TREY DEERE",
                            number: "91",
                            trackingNumber: "1",
                            totalGoalCount: "2",
                        },
                        assist1By: {
                            id: "3748621",
                            title: "CAM PACK  ★",
                            number: "55",
                            trackingNumber: "1",
                            totalGoalCount: "1",
                        },
                        team: {
                            id: 251012,
                            title: "Orangeville Northmen",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                        },
                    },
                    {
                        eventType: "goal",
                        time: "07:23",
                        period: "3",
                        homeTeam: false,
                        powerPlay: false,
                        gameWinningGoal: false,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3770169",
                            title: "CODY MALAWSKY",
                            number: "2",
                            trackingNumber: "4",
                            totalGoalCount: "5",
                        },
                        assist1By: {
                            id: "3770190",
                            title: "NOAH MANNING",
                            number: "3",
                            trackingNumber: "3",
                            totalGoalCount: "9",
                        },
                        assist2By: {
                            id: "3770183",
                            title: "DAVID CHARNEY",
                            number: "15",
                            trackingNumber: "2",
                            totalGoalCount: "4",
                        },
                        team: {
                            id: 251013,
                            title: "Coquitlam Adanacs",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                        },
                    },
                    {
                        eventType: "goal",
                        time: "02:36",
                        period: "3",
                        homeTeam: true,
                        powerPlay: false,
                        gameWinningGoal: false,
                        shg: false,
                        en: false,
                        goalScorer: {
                            id: "3748606",
                            title: "BOWIE HORSMAN  ★",
                            number: "81",
                            trackingNumber: "1",
                            totalGoalCount: "3",
                        },
                        assist1By: {
                            id: "3748611",
                            title: "JOEY SPALLINA  ★",
                            number: "22",
                            trackingNumber: "2",
                            totalGoalCount: "4",
                        },
                        team: {
                            id: 251012,
                            title: "Orangeville Northmen",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                        },
                    },
                ],
                type: "goals",
            },
        ],
        penaltiesByPeriod: [
            {
                period: "1ST Period",
                periodEvents: [
                    {
                        eventType: "penalty",
                        time: "13:49",
                        period: "1",
                        homeTeam: false,
                        major: false,
                        commitedBy: {
                            type: "players",
                            title: "REMO SCHENATO",
                            id: "3770182",
                            number: "17",
                        },
                        servedBy: {
                            id: "",
                            title: "REMO SCHENATO",
                            number: "17",
                        },
                        penaltyType: {
                            title: "Illegal Cross-Checking",
                            duration: "2",
                            class: "minor",
                        },
                        team: {
                            id: 251013,
                            title: "Coquitlam Adanacs",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                        },
                    },
                    {
                        eventType: "penalty",
                        time: "02:59",
                        period: "1",
                        homeTeam: true,
                        major: false,
                        commitedBy: {
                            type: "players",
                            title: "NATE RUFF  ★",
                            id: "3748629",
                            number: "16",
                        },
                        servedBy: {
                            id: "",
                            title: "ELIJAH EDWARDS",
                            number: "13",
                        },
                        penaltyType: {
                            title: "Illegal Cross-Checking",
                            duration: "2",
                            class: "minor",
                        },
                        team: {
                            id: 251012,
                            title: "Orangeville Northmen",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                        },
                    },
                    {
                        eventType: "penalty",
                        time: "00:15",
                        period: "1",
                        homeTeam: true,
                        major: false,
                        commitedBy: {
                            type: "players",
                            title: "ELIJAH EDWARDS",
                            id: "3748613",
                            number: "13",
                        },
                        servedBy: {
                            id: "",
                            title: "ELIJAH EDWARDS",
                            number: "13",
                        },
                        penaltyType: {
                            title: "Illegal Cross-Checking",
                            duration: "2",
                            class: "minor",
                        },
                        team: {
                            id: 251012,
                            title: "Orangeville Northmen",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/ef625612-2785-4a53-7c50-06d64457d800",
                        },
                    },
                ],
                type: "penalty",
            },
            {
                period: "2ND Period",
                periodEvents: null,
                type: "penalty",
            },
            {
                period: "3RD Period",
                periodEvents: [
                    {
                        eventType: "penalty",
                        time: "10:32",
                        period: "3",
                        homeTeam: false,
                        major: false,
                        commitedBy: {
                            type: "players",
                            title: "CODY MALAWSKY",
                            id: "3770169",
                            number: "2",
                        },
                        servedBy: {
                            id: "",
                            title: "CODY MALAWSKY",
                            number: "2",
                        },
                        penaltyType: {
                            title: "Delay of Game",
                            duration: "2",
                            class: "minor",
                        },
                        team: {
                            id: 251013,
                            title: "Coquitlam Adanacs",
                            logo: "https://imagedelivery.net/ErrQpIaCOWR-Tz51PhN1zA/6d83ddb3-f9b9-429e-4964-a9a932c09b00",
                        },
                    },
                ],
                type: "penalty",
            },
        ],
        shots: {
            title: [
                {
                    id: 251013,
                    title: "Coquitlam Adanacs",
                },
                {
                    id: 251012,
                    title: "Orangeville Northmen",
                },
            ],
            final: ["49", "56"],
            shotsByPeriod: [
                {
                    data: ["13", "15"],
                    period: "1ST",
                },
                {
                    data: ["21", "19"],
                    period: "2ND",
                },
                {
                    data: ["15", "22"],
                    period: "3RD",
                },
            ],
        },
        goalieInfoVisitor: {
            title: ["#35 JACK KASK (W)"],
            id: ["3770170"],
            tois: ["60:00"],
            ons: [
                {
                    period: "1",
                    time: "20:00",
                },
            ],
            offs: [
                {
                    period: "3",
                    time: "00:00",
                },
            ],
        },
        goalieInfoHome: {
            title: ["#39 CONNOR O'TOOLE ★ (L)", "Empty Net", "#39 CONNOR O'TOOLE ★"],
            id: ["3748620", "0", "3748620"],
            tois: ["57:08", "00:16", "02:36"],
            ons: [
                {
                    period: "1",
                    time: "20:00",
                },
                {
                    period: "3",
                    time: "02:52",
                },
                {
                    period: "3",
                    time: "02:36",
                },
            ],
            offs: [
                {
                    period: "3",
                    time: "02:52",
                },
                {
                    period: "3",
                    time: "02:36",
                },
                {
                    period: "3",
                    time: "00:00",
                },
            ],
        },
        shootoutSummaryVisitor: {
            playerId: [],
            player: [],
            goalieId: [],
            goalie: [],
            result: [],
            number: [],
        },
        shootoutSummaryHome: {
            playerId: [],
            player: [],
            goalieId: [],
            goalie: [],
            result: [],
            number: [],
        },
    },
};
